### PR TITLE
Test php 7.2 on travis

### PR DESCRIPTION
**Pull request by DaazKu**
Partially addresses https://github.com/vanilla/vanilla/issues/5878

### CODE REVIEW

**Comment by DaazKu** [comment]
Waiting on htmLawed author to update the `create_function` calls.
He's usually pretty fast on addressing issues.

**Comment by DaazKu** [comment]
Depends on https://github.com/vanilla/htmlawed/issues/17

**Comment by greatislander** [comment]
Do you plan to tag a new version shortly? Thanks!

**Comment by DaazKu** [comment]
https://github.com/vanilla/htmlawed/releases/tag/v2.2.4.1

**Pull request merged**
